name: CI

on:
  push:
    branches: [ "dev", "main", "tests", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          cd ./flowers/flowers
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "$default" > default
          echo "Using default scheme: $default"
      - name: Test
        env:
          scheme: ${{ env.default }}
          platform: 'iOS Simulator'
        run: |
          cd ./flowers/flowers
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "Using device: $device"
          if [ -z "$scheme" ]; then
            echo "Error: No scheme provided."
            exit 1
          fi
          xcodebuild test -scheme "$scheme" -destination "platform=$platform,name=$device" -enableCodeCoverage YES || true

  build:
    runs-on: macos-12
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          cd ./flowers/flowers
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "$default" > default
          echo "Using default scheme: $default"
      - name: Build
        env:
          scheme: ${{ env.default }}
          platform: 'iOS Simulator'
        run: |
          cd ./flowers/flowers
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "Using device: $device"
          if [ -z "$scheme" ]; then
            echo "Error: No scheme provided."
            exit 1
          fi
          xcodebuild build -scheme "$scheme" -destination "platform=$platform,name=$device" || true
